'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync(__dirname+'/../app.js','utf8');
const context=vm.createContext({});
for(const name of ['compactMemberLabel','shiftedPlanSlots']) {const at=src.indexOf('function '+name+'(');vm.runInContext(src.slice(at,src.indexOf('\n}',at)+2),context);}
const fixture=()=>[{id:'done',date:'2026-10-09',at:600,min:60,a0:600,a1:650,takes:{A:3}},{id:'a',date:'2026-10-09',at:660,min:60,name:'米村（OCHANORMA）',takes:{A:2}},{id:'b',date:'2026-10-09',at:720,min:60},{id:'tomorrow',date:'2026-10-10',at:660,min:60}];
test('name suffix is display-only and leaves other parentheses and names intact',()=>{assert.equal(context.compactMemberLabel('米村（OCHANORMA）'),'米村');assert.equal(context.compactMemberLabel('米村 (OCHA NORMA)'),'米村');assert.equal(context.compactMemberLabel('鈴木（スタッフ）'),'鈴木（スタッフ）');});
test('advance same-day remaining slots preserving data and other days',()=>{const s=fixture(),before=JSON.stringify(s),n=context.shiftedPlanSlots(s,'a',-5);assert.equal(n[1].at,655);assert.equal(n[2].at,715);assert.equal(n[0],s[0]);assert.equal(n[3],s[3]);assert.equal(n[1].takes,s[1].takes);assert.equal(n[1].name,s[1].name);assert.equal(JSON.stringify(s),before);});
test('repeat shifts validate against actual prior finish and reject overlap atomically',()=>{let s=context.shiftedPlanSlots(fixture(),'a',-5);s=context.shiftedPlanSlots(s,'a',-5);assert.equal(s[1].at,650);const before=JSON.stringify(s);assert.throws(()=>context.shiftedPlanSlots(s,'a',-5),/重なる/);assert.equal(JSON.stringify(s),before);});
test('unknown duplicate active completed and unconfirmed slots are rejected',()=>{for(const change of [s=>s.push({...s[1]}),s=>s[1].a0=660,s=>s[1].a1=720,s=>s[1].scheduleTimeUnconfirmed=true]){const s=fixture();change(s);assert.throws(()=>context.shiftedPlanSlots(s,'a',-5));}assert.throws(()=>context.shiftedPlanSlots(fixture(),'missing',5));assert.throws(()=>context.shiftedPlanSlots(fixture(),'a',NaN));});
test('negative clock shift rejected and next day untouched',()=>{const s=[{id:'a',date:'2026-10-09',at:0,min:60}];assert.throws(()=>context.shiftedPlanSlots(s,'a',-5));});
test('both editor material settings are closed while field adjustment and automatic reception remain reachable',()=>{assert.match(src,/data-settings-panel="rec-materials"><summary>/);assert.match(src,/data-settings-panel="live-materials"><summary>/);assert.match(src,/data-act="pshift"/);assert.match(src,/今から開始/);});
function actionFixture(){
 const s=fixture(),c=vm.createContext({S:{plan:{slots:s}},U:{},VIEW:()=>false,preview:false,recordingInboxCanWrite:()=>true,REC:false,recordingStartPending:false,recordingFinalizePending:false,confirm:()=>true,alert:()=>{},pushUndo:()=>{},pauseRecSchedule:()=>{},save:()=>{},render:()=>{},min2hm:x=>String(x)});
 for(const name of ['compactMemberLabel','shiftedPlanSlots']){const a=src.indexOf('function '+name+'(');vm.runInContext(src.slice(a,src.indexOf('\n}',a)+2),c);}
 const a=src.indexOf('    case "pshiftundo":'),z=src.indexOf('    case "pstart":',a);vm.runInContext('function act(a,id){switch(a){'+src.slice(a,z)+'}}',c);return c;
}
test('field adjustment cancel is a no-op, accepted change can be undone',()=>{const c=actionFixture(),original=JSON.stringify(c.S);c.confirm=()=>false;c.act('pshift','a|-5');assert.equal(JSON.stringify(c.S),original);c.confirm=()=>true;c.act('pshift','a|-5');assert.equal(c.S.plan.slots[1].at,655);c.act('pshiftundo','');assert.equal(JSON.stringify(c.S),original);assert.equal(c.U.planShiftUndo,null);});
test('field undo does not erase subsequent takes or user changes',()=>{const c=actionFixture();c.act('pshift','a|-5');c.S.plan.slots[1].takes.A=9;const before=JSON.stringify(c.S);c.act('pshiftundo','');assert.equal(JSON.stringify(c.S),before);});
test('field shift rejects stale confirmation and active recording',()=>{const c=actionFixture();c.confirm=()=>{c.S.plan.slots[1].at=661;return true;};c.act('pshift','a|-5');assert.equal(c.S.plan.slots[1].at,661);c.REC=true;const before=JSON.stringify(c.S);c.act('pshift','a|5');assert.equal(JSON.stringify(c.S),before);});
