const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync(__dirname+'/../app.js','utf8');const block=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
function manual(file=true,linked=true){const events=[],c=vm.createContext({S:{ghToken:'synthetic',bkGistId:linked?'target':''},U:{},backupInFlight:false,syncing:false,manualSync:false,preview:null,VIEW:()=>false,backupToFile:async()=>{events.push('local-file');return file},syncNow:async()=>events.push('read-reconcile'),doBackup:async()=>events.push('new-cloud')});vm.runInContext(block('async function backupWithCloudCheck()', 'async function doBackup('),c);return {c,events};}
test('manual backup preserves local file before cloud reconciliation',async()=>{const x=manual();await x.c.backupWithCloudCheck();assert.deepEqual(x.events,['local-file','read-reconcile']);});
test('local preservation failure prevents any cloud request',async()=>{const x=manual(false);await x.c.backupWithCloudCheck();assert.deepEqual(x.events,['local-file']);});
test('unlinked existing backup flow is preserved after local file',async()=>{const x=manual(true,false);await x.c.backupWithCloudCheck();assert.deepEqual(x.events,['local-file','new-cloud']);});
function reader({manual=true,wrong=false,cancel=false,invalid=false}={}){let prompts=0,saves=0,files=0;const state={shows:[{id:'old',name:'Kept'}],songs:[],notes:[]},obj={app:invalid?'wrong':'utacheck',at:1,state};const c=vm.createContext({S:{bkGistId:'target',ghToken:'synthetic',bkKey:'old',shows:[{id:'local',name:'Local'}]},syncComparison:null,gh:async()=>({files:{backup:{}}}),backupIndexFile:()=>true,readCloudBackup:async()=>({enc:1}),unpackBackup:async()=>{const e=Error('key');e.badKey=1;throw e},unpackWithPass:async()=>{c.S.bkKey='new';if(wrong)throw Error('key');return obj},prompt:()=>{prompts++;return cancel?null:'synthetic'},save:()=>saves++,download:()=>files++,Date,Number,Array,JSON,Error});vm.runInContext(block('async function readSyncBackup(target)', '// その場で両方向に揃える'),c);return{c,get:()=>({prompts,saves,files}),run:()=>c.readSyncBackup('target',manual)};}
test('manual key confirmation reads cloud and preserves both snapshots without applying remote',async()=>{const x=reader();await x.run();assert.equal(x.c.S.shows[0].id,'local');assert.deepEqual(x.get(),{prompts:1,saves:1,files:1});assert.equal(x.c.syncComparison.cloudShows[0],'Kept');});
for(const options of [{manual:false},{wrong:true},{cancel:true},{invalid:true}])test('failed or background key check does not alter key/content or export invalid remote '+JSON.stringify(options),async()=>{const x=reader(options);await assert.rejects(x.run());assert.equal(x.c.S.bkKey,'old');assert.equal(x.c.S.shows[0].id,'local');assert.equal(x.get().files,0);assert.equal(x.get().saves,0);if(options.manual===false)assert.equal(x.get().prompts,0);});
