const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync(__dirname+'/../app.js','utf8');const block=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
function manual(file=true,linked=true){const events=[],c=vm.createContext({S:{ghToken:'synthetic',bkGistId:linked?'target':''},U:{},backupInFlight:false,syncing:false,manualSync:false,preview:null,VIEW:()=>false,backupToFile:async()=>{events.push('local-file');return file},syncNow:async()=>events.push('read-reconcile'),doBackup:async()=>events.push('new-cloud')});vm.runInContext(block('async function backupWithCloudCheck()', 'async function doBackup('),c);return {c,events};}
test('manual backup preserves local file before cloud reconciliation',async()=>{const x=manual();await x.c.backupWithCloudCheck();assert.deepEqual(x.events,['local-file','read-reconcile']);});
test('local preservation failure prevents any cloud request',async()=>{const x=manual(false);await x.c.backupWithCloudCheck();assert.deepEqual(x.events,['local-file']);});
test('unlinked existing backup flow is preserved after local file',async()=>{const x=manual(true,false);await x.c.backupWithCloudCheck();assert.deepEqual(x.events,['local-file','new-cloud']);});
function reader({manual=true,wrong=false,cancel=false,invalid=false}={}){let prompts=0,saves=0,files=0;const state={shows:[{id:'old',name:'Kept'}],songs:[],notes:[]},obj={app:invalid?'wrong':'utacheck',at:1,state};const c=vm.createContext({S:{bkGistId:'target',ghToken:'synthetic',bkKey:'old',shows:[{id:'local',name:'Local'}]},syncComparison:null,gh:async()=>({files:{backup:{}}}),backupIndexFile:()=>true,readCloudBackup:async()=>({enc:1}),unpackBackup:async()=>{const e=Error('key');e.badKey=1;throw e},unpackWithPass:async()=>{c.S.bkKey='new';if(wrong)throw Error('key');return obj},prompt:()=>{prompts++;return cancel?null:'synthetic'},save:()=>saves++,download:()=>files++,Date,Number,Array,JSON,Error});vm.runInContext(block('async function readSyncBackup(target)', '// その場で両方向に揃える'),c);return{c,get:()=>({prompts,saves,files}),run:()=>c.readSyncBackup('target',manual)};}
test('manual key confirmation reads cloud and preserves both snapshots without applying remote',async()=>{const x=reader();await x.run();assert.equal(x.c.S.shows[0].id,'local');assert.deepEqual(x.get(),{prompts:1,saves:1,files:1});assert.equal(x.c.syncComparison.cloudShows[0],'Kept');});
for(const options of [{manual:false},{wrong:true},{cancel:true},{invalid:true}])test('failed or background key check does not alter key/content or export invalid remote '+JSON.stringify(options),async()=>{const x=reader(options);await assert.rejects(x.run());assert.equal(x.c.S.bkKey,'old');assert.equal(x.c.S.shows[0].id,'local');assert.equal(x.get().files,0);assert.equal(x.get().saves,0);if(options.manual===false)assert.equal(x.get().prompts,0);});
test('read-only inspection preserves local before read and never sends, restores, changes key or prompts',async()=>{
 const events=[],state={shows:[{id:'local',name:'Local Blueprint'}],bkKey:'synthetic-existing',ghToken:'synthetic',bkGistId:'target'},before=JSON.stringify(state);
 const c=vm.createContext({S:state,U:{},syncing:false,backupInFlight:false,manualSync:false,preview:null,syncReadReport:'',VIEW:()=>false,backupToFile:async()=>{events.push('file');return true;},readSyncBackup:async()=>{events.push('read');return{state:{shows:[{id:'remote',name:'Remote'}]}}},render(){},alert(){},doBackup(){throw Error('unexpected write')},restoreBackup(){throw Error('unexpected restore')},prompt(){throw Error('unexpected key input')}});
 vm.runInContext(block('async function inspectCloudBackup()', 'async function backupWithCloudCheck()'),c);await c.inspectCloudBackup();assert.deepEqual(events,['file','read']);assert.equal(JSON.stringify(state),before);assert.match(c.syncReadReport,/Local Blueprint/);assert.equal(c.syncing,false);
});
test('network stage diagnostic contains stage only and excludes error contents and secrets',()=>{const c=vm.createContext({TypeError});vm.runInContext(block('function cloudReadStageError(', 'async function backupFileText'),c);const err=c.cloudReadStageError('GitHub API',new TypeError('Load failed synthetic-secret-token'));assert.match(err.message,/GitHub API/);assert.match(err.message,/network/);assert(!err.message.includes('synthetic-secret-token'));});
for(const stage of ['バックアップ索引','分割ファイル 2/3'])test('raw network failure identifies '+stage+' without URL/auth contents',async()=>{
 const c=vm.createContext({URL,AbortSignal,TypeError,Error,fetch:async()=>{throw new TypeError('Load failed private diagnostic payload');}});vm.runInContext(block('function cloudReadStageError(', 'function backupIndexFile('),c);
 await assert.rejects(c.backupFileText({truncated:true,raw_url:'https://gist.githubusercontent.com/synthetic/raw/1'},stage),e=>e.message.includes(stage)&&e.message.includes('network')&&!e.message.includes('private diagnostic payload')&&!e.message.includes('https://'));
});
test('shared read failure diagnostic does not claim a prior cloud write never happened',()=>{const c=vm.createContext({TypeError});vm.runInContext(block('function cloudReadStageError(', 'async function backupFileText'),c);const err=c.cloudReadStageError('分割ファイル 2/3のraw取得',new TypeError('Load failed'));assert.match(err.message,/分割ファイル 2\/3/);assert(!/送信.*していません|復元.*していません/.test(err.message));});
