'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
const src=fs.readFileSync(__dirname+'/../app.js','utf8');
function setup(){const slot={id:'a',name:'Synthetic',at:720,min:120,a0:87,startAt:123,secStart:456,secCur:'A',takes:{A:3},secLog:{A:4},custom:'keep'};const c=vm.createContext({S:{plan:{slots:[slot]},recs:{audio:'keep'},notes:[{memo:'keep'}]},VIEW:()=>false,preview:false,recordingInboxCanWrite:()=>true,REC:false,recordingStartPending:false,recordingFinalizePending:false,pitchStartPending:false,PT:{on:false},micStream:null,confirm:()=>true,alert:()=>{},pushUndo:()=>{},save:()=>{},render:()=>{},autoMsg:''});const a=src.indexOf('    case "pcancel":'),b=src.indexOf('    case "pretry":',a);vm.runInContext('function act(id){switch("pcancel"){'+src.slice(a,b)+'}}',c);return c;}
test('mistaken start reset preserves takes sections notes and audio, archives only timing',()=>{const c=setup(),before=JSON.parse(JSON.stringify(c.S));c.act('a');const s=c.S.plan.slots[0];assert.equal(s.a0,undefined);assert.equal(s.a1,undefined);assert.equal(s.startAt,undefined);assert.equal(s.secStart,undefined);for(const k of ['takes','secLog','secCur','custom','at','min'])assert.deepEqual(JSON.parse(JSON.stringify(s[k])),before.plan.slots[0][k]);assert.equal(s.cancelledStarts[0].a0,87);assert.equal(s.cancelledStarts[0].startAt,123);assert.deepEqual(c.S.recs,{audio:'keep'});assert.deepEqual(c.S.notes,[{memo:'keep'}]);});
test('cancel confirmation and repeated action do not modify records',()=>{const c=setup(),before=JSON.stringify(c.S);c.confirm=()=>false;c.act('a');assert.equal(JSON.stringify(c.S),before);c.confirm=()=>true;c.act('a');const after=JSON.stringify(c.S);c.act('a');assert.equal(JSON.stringify(c.S),after);});
test('active audio processes completed slots and malformed history reject cancellation',()=>{for(const mutate of [c=>c.REC=true,c=>c.recordingStartPending=true,c=>c.recordingFinalizePending=true,c=>c.pitchStartPending=true,c=>c.PT.on=true,c=>c.micStream={},c=>c.S.plan.slots[0].a1=100,c=>c.S.plan.slots[0].cancelledStarts={}]){const c=setup();mutate(c);const before=JSON.stringify(c.S);c.act('a');assert.equal(JSON.stringify(c.S),before);}});
test('concurrent edit during confirmation is preserved',()=>{const c=setup();c.confirm=()=>{c.S.plan.slots[0].takes.A=9;return true};c.act('a');assert.equal(c.S.plan.slots[0].a0,87);assert.equal(c.S.plan.slots[0].takes.A,9);assert.equal(c.S.plan.slots[0].cancelledStarts,undefined);});
test('after reset the existing schedule adapter applies new time while all work records survive',()=>{const c=setup();c.act('a');const P=require('../private-preparation'),Schedule=require('../recording-schedule-update');const s=c.S.plan.slots[0];Object.assign(s,{day:'10/9',date:'2026-10-09',kind:'member',place:'Synthetic'});const packet={app:'utacheck-recording-schedule-update',version:1,id:'synthetic-new-time',year:2026,timezone:'Asia/Tokyo',updates:[{id:'a',expected:{name:s.name,day:s.day,date:s.date,kind:s.kind,place:s.place,at:720,min:120},next:{at:1140,min:75}}]};const out=P.apply(JSON.parse(JSON.stringify(c.S)),{id:'synthetic-op',type:'recording-schedule',sha256:'a'.repeat(64),packet},{schedule:Schedule.apply}).state;assert.equal(out.plan.slots[0].at,1140);assert.equal(out.plan.slots[0].min,75);assert.equal(out.plan.slots[0].a1,undefined);assert.equal(out.plan.slots[0].takes.A,3);assert.equal(out.plan.slots[0].secLog.A,4);assert.equal(out.plan.slots[0].cancelledStarts[0].a0,87);assert.deepEqual(out.recs,{audio:'keep'});});
