'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../app.js','utf8');
const block=(a,b)=>source.slice(source.indexOf(a),source.indexOf(b,source.indexOf(a)));
function fixture(){
 const state={songs:[{id:'s',lines:[{t:'lyric'}]}],notes:[{id:'n',songId:'s',memo:'note'}],rsongs:[],shows:[],groups:[],members:[],plan:{slots:[]}};
 const c=vm.createContext({S0:{songs:[],notes:[],rsongs:[],shows:[],groups:[],members:[],plan:{slots:[]}},unpackState:x=>x,KEY:'utacheck.v1'});
 vm.runInContext(block('// Read-only startup inspection.', 'async function preserveStartupStorage('),c);
 const snap=(value=state)=>({slots:[{present:true,value:{seq:10,txt:JSON.stringify(value)}},{present:true,value:{seq:9,txt:JSON.stringify(state)}}],legacy:null,broken:[]});
 return {c,state,snap};
}
test('healthy candidate is a new object and retains unknown/private fields',()=>{const {c,state,snap}=fixture();state.extra={kept:1};const snapshot=snap(),before=JSON.stringify(snapshot);const x=c.startupCandidate(snapshot);assert.equal(x.seq,10);assert.equal(x.state.extra.kept,1);assert.equal(JSON.stringify(snapshot),before);});
for(const invalid of [null,[],3,'data',{songs:null},{songs:[null]},{songs:[{id:'s',lines:null}]},{songs:[{id:'s',lines:['bad']}]},{songs:[{id:'s',L:2}],songLib:[[]]},{songs:[{id:'s',L:-1}],songLib:[[]]},{plan:{slots:'bad'}}])test('malformed candidate blocks without promoting the older generation: '+JSON.stringify(invalid),()=>{const {c,snap}=fixture();assert.throws(()=>c.startupCandidate(snap(invalid)));});
test('newest invalid JSON blocks, including with valid older and legacy work',()=>{const {c,snap}=fixture(),s=snap();s.slots[0].value.txt='{';s.legacy=s.slots[1].value.txt;assert.throws(()=>c.startupCandidate(s));});
test('empty saved state is never accepted as the canonical data',()=>{const {c,snap}=fixture();assert.throws(()=>c.startupCandidate(snap({songs:[],notes:[],rsongs:[]})));});
test('legacy local data is accepted only when both IDB slots are absent',()=>{const {c,state}=fixture();assert.equal(c.startupCandidate({slots:[{present:false},{present:false}],legacy:JSON.stringify(state),broken:[]}).state.notes.length,1);});
test('true first installation differs from recovery originals with missing active slots',()=>{const {c}=fixture(),s={slots:[{present:false},{present:false}],legacy:null,broken:[]};assert.equal(c.startupCandidate(s).seq,0);s.broken=['utacheck.v1:broken:1'];assert.throws(()=>c.startupCandidate(s));});
test('equal sequence with different contents is ambiguous and blocked',()=>{const {c,snap}=fixture(),s=snap();s.slots[1].value.seq=10;s.slots[1].value.txt='{}';assert.throws(()=>c.startupCandidate(s));});
test('unexplained differing legacy primary blocks older IDB authority',()=>{const {c,snap,state}=fixture(),s=snap();s.legacy=JSON.stringify({...state,notes:[{id:'newer',memo:'Later fallback edit'}]});assert.throws(()=>c.startupCandidate(s));s.legacy=s.slots[0].value.txt;assert.equal(c.startupCandidate(s).state.notes[0].id,'n');});
test('bad sequence and malformed present envelope cannot masquerade as absence',()=>{const {c,snap}=fixture();for(const value of [null,{}, {txt:'{}',seq:-1},{txt:'{}',seq:'10'},{txt:'{}',seq:Infinity}]){const s=snap();s.slots[0].value=value;assert.throws(()=>c.startupCandidate(s));}});
test('both reads are attempted; either rejection fails closed even if legacy data exists',async()=>{for(const broken of ['state:0','state:1']){const {c}=fixture(),read=[];c.idbGet=async key=>{read.push(key);if(key===broken)throw Error('private');return {seq:1,txt:'{}'};};c.localStorage={getItem:()=>'{"songs":[]}'};await assert.rejects(c.readStartupStorage());assert.deepEqual(read,['state:0','state:1']);}});
test('localStorage read rejection also blocks a healthy IDB startup',async()=>{const {c,state}=fixture();c.idbGet=async()=>({seq:1,txt:JSON.stringify(state)});c.localStorage={getItem(){throw Error('quota/private');}};await assert.rejects(c.readStartupStorage());});
test('blocked lifecycle event does not commit fields or schedule saves',()=>{const handlers={},called=[];const c=vm.createContext({window:{addEventListener:(t,fn)=>handlers[t]=fn},document:{hidden:true,addEventListener:(t,fn)=>handlers[t]=fn},recordingInboxCanWrite:()=>false,flushSheet:()=>called.push('sheet'),commitFields:()=>called.push('fields'),save:()=>called.push('save'),saveNow:()=>called.push('flush')});vm.runInContext(block('window.addEventListener("pagehide", () => { if (!recordingInboxCanWrite())', 'if ("serviceWorker" in navigator)'),c);handlers.pagehide();handlers.visibilitychange();assert.deepEqual(called,[]);});
test('freeSpace cannot delete broken or recording-only recovery originals',()=>{const c=vm.createContext({recordingInboxStorageRemove(){throw Error('must not delete');}});vm.runInContext(block('function freeSpace()', '// 保存はIndexedDBへ。'),c);assert.equal(c.freeSpace(),0);});
test('editor entry remains blocked when optional integration is absent',()=>{const c=vm.createContext({recordingInboxIntegration:null,recordingInboxCanWrite:()=>false});vm.runInContext(block('function enterRecordingInboxEditor()', 'function withRecordingInboxEditor('),c);assert.equal(c.enterRecordingInboxEditor(),null);});
test('startup migration rethrows errors from the formerly tolerant conversion block',()=>{const c=vm.createContext({S:{songs:[],rsongs:[],tagWords:{}}});vm.runInContext(block('function migrate({preserve', '  // 旧データの引き継ぎ：公演名')+'\n}',c);assert.throws(()=>c.migrate({preserve:true}),/map/);assert.doesNotThrow(()=>c.migrate());});
