const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const XLSX=require('../vendor/xlsx.full.min.js');
const source=fs.readFileSync(require('node:path').join(__dirname,'../app.js'),'utf8');
function fn(name){const i=source.indexOf('function '+name+'(');assert(i>=0,name);return source.slice(source.lastIndexOf('\n',i)+1,source.indexOf('\n}',i)+2);}
function fixture(){let id=0;const c=vm.createContext({XLSX,Uint8Array,DataView,TextDecoder,Date,uid:()=>String(++id),NAMECELL:/^[A-Z]$/,cleanName:n=>n.replace(/\.(docx|doc|pdf)$/i,''),finalize:(title,credit,rows)=>({title,credit,lines:rows})});for(const n of ['softText','cleanText','wordParagraphText','parseLegacyDoc','parseDocx','parseWordSong','assignOwners','parsePage','parsePDF'])vm.runInContext(fn(n),c);return c;}
function docx(xml){const c=XLSX.CFB.utils.cfb_new();XLSX.CFB.utils.cfb_add(c,'word/document.xml',Buffer.from(xml));return XLSX.CFB.write(c,{type:'buffer',fileType:'zip',compression:true});}
const file=(name,data)=>({name,arrayBuffer:async()=>new Uint8Array(data).buffer});
const wrap=body=>'<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>'+body+'</w:body></w:document>';
function legacy(text,flags=0){const word=Buffer.alloc(1024+text.length*2);word.writeUInt16LE(0xa5ec,0);word.writeUInt16LE(0xc1,2);word.writeUInt16LE(flags,10);word.writeUInt16LE(14,32);word.writeUInt16LE(22,62);word.writeUInt32LE(text.length,76);word.writeUInt16LE(93,152);word.writeUInt32LE(0,418);word.writeUInt32LE(21,422);word.write(text,1024,'utf16le');const table=Buffer.alloc(21);table[0]=2;table.writeUInt32LE(16,1);table.writeUInt32LE(text.length,9);table.writeUInt32LE(1024,15);const c=XLSX.CFB.utils.cfb_new();XLSX.CFB.utils.cfb_add(c,'WordDocument',word);XLSX.CFB.utils.cfb_add(c,flags&512?'1Table':'0Table',table);return XLSX.CFB.write(c,{type:'buffer'});}
test('compressed DOCX imports without native compression APIs and keeps run/soft-break order',async()=>{const c=fixture();const so=await c.parseDocx(file('歌詞.docx',docx(wrap('<w:p><w:r><w:t>一行</w:t></w:r><w:r><w:t>目です</w:t><w:br/><w:t>二行目です</w:t><w:tab/><w:t>&amp; &#x1F3B5;</w:t></w:r></w:p>'))));assert.deepEqual(Array.from(so.lines,l=>l.t),['一行目です','二行目です & 🎵']);assert.equal(so.title,'歌詞');});
test('paragraphs, blank separators, deletion and column breaks preserve usable lyrics',async()=>{const c=fixture();const so=await c.parseDocx(file('歌詞.docx',docx(wrap('<w:p><w:r><w:t>残す</w:t></w:r><w:del><w:r><w:delText>消す</w:delText></w:r></w:del></w:p><w:p/><w:p><w:r><w:br w:type="column"/><w:t>次の段</w:t></w:r></w:p>'))));assert.equal(so.lines.filter(l=>l.t).length,2);assert(so.lines.find(l=>l.t==='次の段').brk);assert(so.lines.some(l=>l.gap));});
test('empty DOCX and a non-Word ZIP fail rather than importing an invisible empty song',async()=>{const c=fixture();await assert.rejects(c.parseDocx(file('empty.docx',docx(wrap('<w:p/>')))),/読み取れる文字/);await assert.rejects(c.parseDocx(file('bad.docx',Buffer.from('bad'))),/Word/);});
test('legacy DOC reads Japanese Unicode and the chosen table stream',async()=>{for(const flags of [0,512]){const so=await fixture().parseDocx(file('昔の歌詞.doc',legacy('一行目です\r二行目です\r',flags)));assert.deepEqual(Array.from(so.lines,l=>l.t),['一行目です','二行目です']);}});
test('encrypted and truncated legacy Word documents produce explicit failures',async()=>{await assert.rejects(fixture().parseDocx(file('locked.doc',legacy('秘密',256))),/パスワード/);const c=XLSX.CFB.utils.cfb_new();XLSX.CFB.utils.cfb_add(c,'WordDocument',Buffer.from('bad'));await assert.rejects(fixture().parseDocx(file('bad.doc',XLSX.CFB.write(c,{type:'buffer'}))),/Word形式/);});
test('Word converts to the live song row format without losing lyrics',async()=>{const c=fixture();const so=await c.parseWordSong(file('歌詞.docx',docx(wrap('<w:p><w:r><w:t>テスト歌詞</w:t></w:r></w:p>'))));assert.deepEqual(JSON.parse(JSON.stringify(so.lines)),[['','テスト歌詞']]);});
test('short text PDF imports and retains the first lyric line near page top',async()=>{const c=fixture();c.pdfjsLib={GlobalWorkerOptions:{},getDocument:()=>({promise:Promise.resolve({numPages:1,getPage:async()=>({getViewport:()=>({height:842}),getTextContent:async()=>({items:[{str:'冒頭の歌詞',transform:[1,0,0,1,30,810]},{str:'次の歌詞',transform:[1,0,0,1,30,785]}]})})})})};const so=await c.parsePDF(file('歌詞.pdf',[]));assert.deepEqual(Array.from(so.lines.filter(r=>r[1]),r=>r[1]),['冒頭の歌詞','次の歌詞']);});
test('image-only PDF gives an actionable error',async()=>{const c=fixture();c.pdfjsLib={GlobalWorkerOptions:{},getDocument:()=>({promise:Promise.resolve({numPages:1,getPage:async()=>({getViewport:()=>({height:842}),getTextContent:async()=>({items:[]})})})})};await assert.rejects(c.parsePDF(file('画像.pdf',[])),/画像のみ/);});
module.exports={legacy,docx,wrap};

test("self-closing empty paragraphs stay separate from the following paragraph",async()=>{const so=await fixture().parseDocx(file("歌詞.docx",docx(wrap("<w:p><w:r><w:t>前</w:t></w:r></w:p><w:p/><w:p><w:r><w:t>後</w:t></w:r></w:p>"))));assert.deepEqual(Array.from(so.lines,l=>l.t),["前","","後"]);});
